upgraded all packages to latest. this involved VS editing a bunch of files, and some of them were updated automatically in ways that generated diffs that aren't related to the upgrades (which i kept).
exception: didn't upgrade fody, which requires a cecil with a new api (currently in beta, also breaks our visitor). go to its most recent non-beta-dependent package.